#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2021 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    enable_language_specific_leader = false
    windows_smartclose = ''
    snippet_engine = "neosnippet"
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "OceanicNext"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    filemanager = "nerdtree"

# [[layers]]
# name = "colorscheme"
# colorscheme = "OceanicNext"
# colorscheme_bg = "dark"
# random_theme = true
# frequency = "daily"

# add custom_plugins: https://github.com/mhartington/oceanic-next
[[custom_plugins]]
repo = "Lilja/vim-chezmoi"
merged = 0

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "fzf"
[[layers]]
name = "denite"
[[layers]]
name = 'git'
[[layers]]
name = "github"
[[layers]]
name = 'VersionControl'
[[layers]]
name = "lang#toml"

[[layers]]
name = "lang#javascript"
auto_fix = true
enable_flow_syntax = true
format_on_save = true

[[layer]]
name = 'lang#ruby'
format_on_save = true
ruby_file_head = [
    '#!/usr/bin/ruby -w',
    '# -*- coding: utf-8 -*-',
    '',
    ''
]
enabled_linters = ['rubylint', 'rubocop']
repl_command = "/usr/bin/pry"

[[layers]]
name = 'lang#python'
# python_interpreter = 'D:\scoop\shims\python.exe'
enabled_linters = ['python', 'pylint']
# enable_typeinfo = true
format_on_save = true
python_file_head = [
    '#!/usr/bin/env python3',
    '# -*- coding: utf-8 -*-',
    '',
    ''
]

[[layers]]
name = "lang#sh"
format_on_save = true
bash_file_head = [
    '#!/usr/bin/env bash',
    '#=============================================================================',
    '# filename.sh --- bash script',
    '# Copyright (c) 2050 @EasyQuest',
    '# Author: {{ .name }} < {{ .email }} >',
    '# URL: https://easy-quest.github.io/web/',
    '#=============================================================================',
    'cat <<\ZZZ',
    ' _____                 ___                  _',
    '| ____|__ _ ___ _   _ / _ \ _   _  ___  ___| |_',
    '|  _| / _` / __| | | | | | | | | |/ _ \/ __| __|',
    '| |__| (_| \__ \ |_| | |_| | |_| |  __/\__ \ |_',
    '|_____\__,_|___/\__, |\__\_\\__,_|\___||___/\__|',
    '                |___/',
    'ZZZ',
    '',
    ''
]

[[layers]]
name = 'lsp'
enabled_clients = ['pyright']

[[layers]]
name = "format"

[[layers]]
name = "lang#go"
[[layers]]
name = "lang#goby"
[[layers]]
name = "lang#livescript"
[[layers]]
name = "lang#markdown"
enabled_formater = ["remark", "prettier"]
enableWcwidth = "Enable"
format_on_save = true

[[layers]]
name = "lang#perl"

[[layers]]
name = "lang#tmpl"

